import './mangoRepo/01_basic.ts'
import './mangoRepo/02_feature_idMapping.ts'
import './mangoRepo/03_feature_idTransformation.ts'
import './mangoRepo/04_feature_idMapping_with_idTransformation.ts'
import './mangoRepo/05_feature_returnLatestDocumentByDefault.ts'
import './mangoRepo/99_cleanup.ts'
